version: '3.8'

services:
  frontend:
    build: ./dofd-05-kajihan
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://backend:5000/api

  backend:
    build: ./dotnet-app-kajihan
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Initial Catalog=Products;User=sa;Password=Passw0rd!;TrustServerCertificate=True
    entrypoint: ["bash", "-c", "dotnet Products.dll"]

  db:
    build: ./db-init
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!
      - MSSQL_PID=Developer    
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "if [ ! -f /tmp/health.txt ]; then touch /tmp/health.txt && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw0rd! -i /init-script_go.sql || exit 0 ; else echo 'The database migration is complete.'; fi"]
      interval: 30s
      timeout: 10s
      retries: 1
    